file_format: "1"
id: bat_board
name: Bat Board
type: shield
url: https://github.com/powkhenai
requires: [nice_nano_v2]
features:
  - keys
  - underglow
siblings:
  - bat_board_left
  - bat_board_right
